// src/ui/components/forms/GeneralForm.vue
<script setup lang="ts">
import { computed } from 'vue';
import usePluginStore from '@/stores/plugin';
import Field from '../Field.vue';

const store = usePluginStore();

const settings = computed(() => store.data!.frame.settings);

const backgroundColors = computed(() => [
  { label: '- None -', value: '' },
  ...Object.keys(store.data!.colors).map((name) => ({ label: name, value: name })),
]);

const versions = ['10.x', '9.x', '8.x', '7.x', '6.x', '5.x'];
const shapeRenderings = ['auto', 'optimizeSpeed', 'crispEdges', 'geometricPrecision'];
</script>

<template>
  <Field label="Title">
    <InputText v-model="settings.title" fluid size="small" />
  </Field>
  <Field label="DiceBear version">
    <Select
      v-model="settings.dicebearVersion"
      :options="versions"
      fluid
      size="small"
    />
  </Field>
  <Field label="Background Color">
    <Select
      v-model="settings.backgroundColorGroupName"
      :options="backgroundColors"
      option-label="label"
      option-value="value"
      fluid
      size="small"
    />
  </Field>
  <Field label="Shape Rendering">
    <Select
      v-model="settings.shapeRendering"
      :options="shapeRenderings"
      fluid
      size="small"
    />
  </Field>
  <Field label="Precision">
    <InputNumber
      v-model="settings.precision"
      :min="0"
      :max="8"
      fluid
      size="small"
    />
  </Field>
</template>

// src/ui/features/style/components/GeneralForm.tsx
import { Input } from '@/components/ui/input';
import { FieldRow } from '@/components/fields/FieldRow';
import { NumberInput } from '@/components/fields/NumberInput';
import { SimpleSelect } from '@/components/fields/SimpleSelect';
import { useAppStore } from '@/store';

const SHAPE_RENDERINGS = ['auto', 'optimizeSpeed', 'crispEdges', 'geometricPrecision'];

export function GeneralForm() {
  const data = useAppStore((state) => state.style.data)!;
  const update = useAppStore((state) => state.updateFrameSettings);
  const settings = data.frame.settings;

  const backgroundOptions = Object.keys(data.colors).map((name) => ({ label: name, value: name }));

  return (
    <>
      <FieldRow label="Title">
        <Input value={settings.title} onChange={(event) => update({ title: event.target.value })} />
      </FieldRow>
      <FieldRow label="Background color">
        <SimpleSelect
          value={settings.backgroundColorGroupName || null}
          emptyLabel="None"
          options={backgroundOptions}
          onChange={(value) => update({ backgroundColorGroupName: value ?? '' })}
        />
      </FieldRow>
      <FieldRow label="Shape rendering">
        <SimpleSelect
          value={settings.shapeRendering}
          options={SHAPE_RENDERINGS.map((value) => ({ label: value, value }))}
          onChange={(value) => update({ shapeRendering: value! })}
        />
      </FieldRow>
      <FieldRow label="Precision">
        <NumberInput
          value={settings.precision}
          min={0}
          max={8}
          onCommit={(value) => update({ precision: Math.round(value) })}
        />
      </FieldRow>
    </>
  );
}
