// src/ui/components/forms/LicenseForm.vue
<script setup lang="ts">
import { computed } from 'vue';
import usePluginStore from '@/stores/plugin';
import { useDefinitionFile } from '@/utils/useDefinitionFile';
import Field from '../Field.vue';

const store = usePluginStore();

const settings = computed(() => store.data!.frame.settings);
const isDefinition = computed(() => useDefinitionFile(settings.value.dicebearVersion));
</script>

<template>
  <Field label="Source Title">
    <InputText v-model="settings.sourceTitle" fluid size="small" />
  </Field>
  <Field label="Source URL">
    <InputText v-model="settings.source" fluid size="small" />
  </Field>
  <Field label="Creator">
    <InputText v-model="settings.creator" fluid size="small" />
  </Field>
  <Field label="Homepage URL">
    <InputText v-model="settings.homepage" fluid size="small" />
  </Field>
  <Field label="License Name">
    <InputText v-model="settings.licenseName" fluid size="small" />
  </Field>
  <Field label="License URL">
    <InputText v-model="settings.licenseUrl" fluid size="small" />
  </Field>
  <Field v-if="isDefinition" label="License Text">
    <Textarea v-model="settings.licenseText" rows="6" fluid />
  </Field>
</template>

// src/ui/features/style/components/LicenseForm.tsx
import type { FrameSettings } from '@shared/types';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { FieldRow } from '@/components/fields/FieldRow';
import { useAppStore } from '@/store';

const FIELDS: { key: keyof FrameSettings; label: string }[] = [
  { key: 'sourceTitle', label: 'Source title' },
  { key: 'source', label: 'Source URL' },
  { key: 'creator', label: 'Creator' },
  { key: 'homepage', label: 'Homepage URL' },
  { key: 'licenseName', label: 'License name' },
  { key: 'licenseUrl', label: 'License URL' },
];

export function LicenseForm() {
  const settings = useAppStore((state) => state.style.data!.frame.settings);
  const update = useAppStore((state) => state.updateFrameSettings);

  return (
    <>
      {FIELDS.map(({ key, label }) => (
        <FieldRow key={key} label={label}>
          <Input value={String(settings[key])} onChange={(event) => update({ [key]: event.target.value })} />
        </FieldRow>
      ))}
      <FieldRow label="License text">
        <Textarea
          rows={6}
          value={settings.licenseText}
          onChange={(event) => update({ licenseText: event.target.value })}
        />
      </FieldRow>
    </>
  );
}
